
-- Fix Missing Customers in KV Store (kv_store_e0d9c111)
-- This script inserts users into the KV store if they exist in auth.users but are missing from the KV store.

INSERT INTO public.kv_store_e0d9c111 (key, value)
SELECT 
    'team-member:' || au.id,
    jsonb_build_object(
        'id', au.id,
        'email', au.email,
        'name', COALESCE(au.raw_user_meta_data->>'name', au.email),
        'role', 'Client',
        'status', 'active',
        'createdAt', to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
        'updatedAt', to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
        'specialties', '[]'::jsonb,
        'services', '[]'::jsonb
    )
FROM auth.users au
WHERE au.email IN (
    'gabrielssa@gmx.com',
    'camilla.holmblad@gmail.com',
    'dahlcamilla@yahoo.dk',
    'eilahtant@gmail.com',
    'emmajuul@hotmail.com',
    'fx_dev@wezet.xyz',
    'fx@fxcreativestudio.com',
    'hanna@wezet.xyz',
    'helle@slankfitogfri.dk',
    'henriettearff@live.dk',
    'henriras@hotmail.com',
    'j.sabalic@gmail.com',
    'jacob@playminds.dk',
    'javigaoses@gmail.com',
    'jean@nimagency.com',
    'marie.ahlmann@gmail.com',
    'michellejust@hotmail.dk',
    'mkolle@gmail.com',
    'nicolinenoramail@gmail.com',
    'nikolinemeincke@gmail.com',
    'saidi.sarra@live.com',
    'saszeline@theassana.com',
    'sofiasarabande@gmail.com',
    'sophiahindkjaer@outlook.com',
    'sophiethorsoe@gmail.com',
    'stig@ditliv.nu',
    'thojland@hotmail.com',
    'vedskovrajaa@gmail.com',
    'vidailys14@gmail.com',
    'evanllaness@gmail.com',
    'sven@krauch.dk',
    'amt@dahllaw.dk',
    'minawilmot@live.com',
    'vibekesundoo@hotmail.com',
    'sfredskov@hotmail.com',
    'millieelouna@gmail.com',
    'lise_skovsted@hotmail.com',
    'gracekindall@gmail.com',
    'l.markfoged@gmail.com',
    'tatjanavandentempel@gmail.com',
    'alennings@hotmail.com',
    'lise_daugaard@hotmail.com',
    'chrc@jyskebank.dk',
    'henriques.busck@gmail.com',
    'clarissa@newmail.dk',
    'holtenolsen@hotmail.com',
    'simon-voss@hotmail.com',
    'voss.sims@gmail.com',
    'bsmoller9@gmail.com',
    'peterm@tuta.com',
    'bfk@live.dk',
    'linda.m.burlin@gmail.com',
    'lineayokromann@gmail.com',
    'ulrich@irgrens.nu',
    'charlotte@muenster.dk',
    'anna@stwentyfive.com',
    'rww@wedellsborg.com',
    'isaraimyoga@gmail.com',
    'support@latepoint.com',
    'info@stylebyac.com',
    'aws@sycorax.dk',
    'rillet-sideblikke.1n@icloud.com',
    'mettekrusepetersen@me.com',
    'celikkiyan@gmail.com',
    'kiyanacelik@gmail.com',
    'nicolai_littrup@msn.com',
    'klaus.lorenzen@mail.dk',
    'alice@stadilfamily.com',
    'ullamou@gmail.com',
    'friismaler@gmail.com',
    'info@christinaheick.dk',
    'signevaupel@hotmail.com',
    'lonekraskow@live.dk',
    'camillacederholm@yahoo.dk',
    'stinevaleur@hotmail.com',
    'stroeh@msn.com',
    'maikenharris@me.com',
    'hilltherese@hotmail.com',
    'gryknoop@hotmail.com',
    'hanna@lespot.com',
    'karingronningthorup@gmail.com',
    'kristine.raffel@gmail.com',
    'signevaupel@icloud.com',
    'elisabeth@ungar.dk',
    'randiblangsted@icloud.com',
    'famhedegaardlonvig@gmail.com',
    'dr@lindeblad.dk',
    'info@theresehill.com',
    'benedictechegaray@icloud.com',
    'jdenoailles@me.com',
    'aimeerfoto@aol.com',
    'clairesark@yahoo.fr',
    'marie@domainedecanaille.com',
    'gwhite@borlettigroup.com',
    'trinefn@gmail.com',
    'millepraastrup@gmail.com',
    'benedictechegaray@gmail.com',
    'lb@ufuse.com',
    'gry@hungryminds.dk',
    'apreisler68@hotmail.com',
    'stephaniecastella@gmail.com',
    'kr@karolineraben.com',
    'miabdalgas@gmail.com',
    'eww_dk@hotmail.com',
    'pia@oigaard.dk',
    'ms@msoegaard.dk',
    'steph@castellacare.dk',
    'ulrika@producercph.com',
    'linda.algreen@yahoo.dk',
    'annesophieravnholt@gmail.com',
    'dortheejen@hotmail.com',
    'metta.andreasen@gmail.com',
    'kastrala@icloud.com',
    'cnnjac@gmail.com',
    'birgitte.loenvig@gmail.com',
    'peter.andreasen@sonova.com',
    'sia.rosenkrans@gmail.com',
    'mail@mariakringelbach.dk',
    'anja@bourup.dk',
    'lenakaasgaard@gmail.com',
    'a@annahedgaard.dk',
    'hanna@olelynggaard.dk',
    'k.strandberg.larsen@gmail.com',
    'susannesuhr@hotmail.com',
    'louiseth@gmail.com',
    'karina.t@me.com',
    'henrikmarstrand2002@gmail.com',
    'cstegeager@gmail.com',
    'kinewing@hotmail.com',
    'christabormann@gmail.com',
    'soren@olelynggaard.dk',
    'mroffbeat@kyodaimusic.com',
    'amyphillipspilates@gmail.com',
    'brat50000@gmail.com',
    'veronica@assistansjuristerna.se',
    'gary@metafenixgroup.com',
    'dge.marine@gmail.com',
    'raphael.aviges@gmail.com',
    'andrealucia.gauthier@gmail.com',
    'penni2ct@gmail.com',
    'barbara@scheel.com',
    'florence@evidence-events.com'
)
AND NOT EXISTS (
    SELECT 1 FROM public.kv_store_e0d9c111 WHERE key = 'team-member:' || au.id
);

-- Output results
SELECT count(*) as inserted_customers FROM public.kv_store_e0d9c111
WHERE key LIKE 'team-member:%';
